### ISSUE TITLE
上传图标报错

### ISSUE THREAD

**Issue by llsldwy** [bolin-L/nicon#15]
您好，之前版本低的问题，我自己升级解决了，现在启动后，上传图标报错。尝试了半天，感觉不是文件夹权限的问题。
[E] [2022-07-07 01:17:43.594] - TypeError: Cannot read properties of undefined (reading 'file')
    at IconDraftController.saveDraftIcon (/Users/front4/code/nicon-master/server/controller/iconDraftController.js:49:39)
    at /Users/front4/code/nicon-master/server/router/iconDraftRouter.js:31:34
    at dispatch (/Users/front4/code/nicon-master/node_modules/koa-compose/index.js:42:32)
    at /Users/front4/code/nicon-master/server/middleware/auth.js:13:19
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Users/front4/code/nicon-master/node_modules/koa-session2/index.js:32:9
    at async serve (/Users/front4/code/nicon-master/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/front4/code/nicon-master/node_modules/koa-bodyparser/index.js:82:48)
    at async /Users/front4/code/nicon-master/index.js:83:9
    at async /Users/front4/code/nicon-master/index.js:50:28

**Comment by bolin-L** [comment]
这个问题我本地升级验证的时候碰到了  是因为bodyParser中间件解析文件失效了，我把相关依赖升级了改了下写法就好了，但是我还没按么快发布新版本，我需要本地验证过才行

**Comment by bolin-L** [comment]
我把upgrade分支推上来了，你可以切到这个分支试试，等稳定了我再合到master

**Comment by llsldwy** [comment]
@bolin-L 十分感谢🙏
